--27
INSERT INTO sport_facitility
	(name, type, address_id)
VALUES
	('Arena Warszawa 1', 'hala sportowa', 5),
	('Plywalnia Warszawa 1', 'basen', 6),
	('Stadion Warszawa 1', 'stadion', 7),
	('Arena Warszawa 2', 'hala sportowa', 8),
	('Kort Tenisowy Warszawa 1', 'kort tenisowy', 9),
	('Lodowisko Warszawa 1', 'lodowisko', 10),
	('Plywalnia Wroclaw 1', 'basen', 11),
	('Stadion Wroclaw 1', 'stadion', 12),
	('Kort Tenisowy Wroclaw 1', 'kort tenisowy', 13),
	('Arena Wroclaw 1', 'hala sportowa', 14),
	('Lodowisko Wroclaw 1', 'lodowisko', 15),
	('Pole golfowe Wroclaw 1', 'pole golfowe', 16),
	('Pole golfowe Poznan 1', 'pole golfowe', 17),
	('Arena Poznan 1', 'hala sportowa', 18),
	('Plywalnia Poznan 1', 'basen', 19),
	('Kort Tenisowy Poznan 1', 'kort tenisowy', 20),
	('Arena Gdansk 1', 'hala sportowa', 21),
	('Stadion Gdansk 1', 'stadion', 22),
	('Plywalnia Gdansk 1', 'basen', 23),
	('Arena Gdansk 2', 'hala sportowa', 24),
	('Arena Gdansk 3', 'hala sportowa', 25),
	('Arena Gdansk 4', 'hala sportowa', 26),
	('Tauron Arena Krakow', 'hala sportowa', 27),
	('Stadion Krakow 1', 'stadion', 28),
	('Plywalnia Krakow 1', 'basen', 29),
	('Lodowisko Krakow 1', 'losowisko', 30),
	('Stadion Krakow 2', 'stadion', 31),
	('Stok narciarski Zakopane 1', 'stok narciarski', 32),
	('Stok saneczkowy Zakopane 1', 'stok saneczkowy', 33),
	('Skocznia narciarska Engleberg', 'skocznia narciarska', 34),
	('Skocznia narciarska Planica', 'skocznia narciarska', 35);