INSERT INTO address
	(address_id, city, street, building_number)
VALUES
    (5, 'Warszawa', 'Pulawska', '130'),
    (6, 'Warszawa', 'Jana Pawla II', '53'),
	(7, 'Warszawa', 'Konwiktorska', '16A'),
	(8, 'Warszawa', 'Batorego', '67'),
	(9, 'Warszawa', 'Wolska', '92B'),
	(10, 'Warszawa', 'Wawelska', '162'),
	(11, 'Wroclaw', 'Sienkiewicza', '58'),
	(12, 'Wroclaw', 'Mala', '79B'),
	(13, 'Wroclaw', 'Bonifraterska', '69'),
	(14, 'Wroclaw', 'Rozana', '120'),
	(15, 'Wroclaw', 'Legionow', '29'),
	(16, 'Wroclaw', 'Poznanska', '73'),
	(17, 'Poznan', 'Wroclawska', '49'),
	(18, 'Poznan', 'Wielkopolska', '89'),
	(19, 'Poznan', 'Biskupinska', '11A'),
	(20, 'Poznan', 'Kondratowicza', '123'),
	(21, 'Gdansk', 'Gdynska', '51'),
	(22, 'Gdansk', 'Sopocka', '10'),
	(23, 'Gdansk', 'Pomorska', '98'),
	(24, 'Gdansk', 'Neptuna', '67'),
	(25, 'Gdansk', 'Aleja Niepodleglosci', '97'),
	(26, 'Gdansk', 'Mickiewicza', '23'),
	(27, 'Krakow', 'Lema', '7'),
	(28, 'Krakow', 'Monte Cassino', '31'),
	(29, 'Krakow', 'Reymonta', '53'),
	(30, 'Krakow', 'Pilsudskiego', '79'),
	(31, 'Krakow', 'Armii Krajowej', '161'),
	(32, 'Zakopane', 'Wislanska', '1'),
	(33, 'Zakopane', 'Zimowa', '51'),
	(34, 'Engelberg', 'Engelberg Street', '1'),
	(35, 'Planica', 'Planica Street', '1');